name: projectmobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_local_notifications: ^17.2.0
  flutter_secure_storage: ^8.0.0
  geolocator: ^10.0.1
  google_fonts: ^6.2.1
  http: ^1.2.0
  intl: ^0.19.0
  lottie: ^3.1.0
  path: ^1.9.1
  permission_handler: ^11.3.1
  sqflite: ^2.4.2
  timezone: ^0.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lungs.json
    - assets/loading.json
    - assets/air.json
    - assets/breathing_exercise.json
